# site settings
title: ITL
subtitle: Workshop Factory
email: itl@pratt.edu
description: A repository of technology workshops<br /> hosted by the ITL.
baseurl: "/itlworkshops" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 200 Willoughby Avenue Engineering Building 002
city: Brooklyn
state: NY
zip_code: 11205
country: United States of America
phone: (718) 399-4267

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://facebook.com/
github_url: https://github.com/
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url: https://slack.com/
twitter_url: https://twitter.com/

# build settings
markdown: kramdown

sass:
  style: compressed
